<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/catalog/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/(\\?sphrase_id=[0-9]+|index.php.*)*#",
		"RULE" => "IBLOCK_CODE=\$1",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/iblock.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/(\\?sphrase_id=[0-9]+|index.php.*)*#",
		"RULE" => "IBLOCK_CODE=\$1",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/iblock.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/(\\?sphrase_id=[0-9]+|index.php.*)*#",
		"RULE" => "IBLOCK_CODE=\$1",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/iblock.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/([a-z0-9_-]+)/([a-z0-9_-]+)/([a-z0-9_-]+)/(\\?sphrase_id=[0-9]+|index.php.*)*#",
		"RULE" => "IBLOCK_CODE=\$1",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/iblock.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/([a-z0-9_-]+)/([a-z0-9_-]+)/(\\?sphrase_id=[0-9]+|index.php.*)*#",
		"RULE" => "IBLOCK_CODE=\$1",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/iblock.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/([a-z0-9_-]+)/(\\?sphrase_id=[0-9]+|\\?arrFilter_.*)*#",
		"RULE" => "IBLOCK_CODE=\$1",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/iblock.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/brand/([a-zA-Zа-яА-Я0-9_-]+)/([a-zA-Zа-яА-Яa-z0-9_-]+)/*#",
		"RULE" => "brand=\$1&subbrand=\$2",
		"ID" => "mht:offers",
		"PATH" => "/brand/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/ruchnoy_instrument_i_prisposobleniya/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/ruchnoy_instrument_i_prisposobleniya/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/instrument_malyarno_shtukaturnyy/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/instrument_malyarno_shtukaturnyy/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/silovaya_i_stroitelnaya_tekhnika/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/silovaya_i_stroitelnaya_tekhnika/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/sredstva_individualnoy_zashchity/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/sredstva_individualnoy_zashchity/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/raskhodnye_materialy_i_osnastka/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/raskhodnye_materialy_i_osnastka/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/aksessuary_dlya_vannoy_komnaty/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/aksessuary_dlya_vannoy_komnaty/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/lestnitsy_stremyanki_telezhki/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/lestnitsy_stremyanki_telezhki/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/sadovyy_instrument_i_inventar/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/sadovyy_instrument_i_inventar/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/tovary_dlya_aktivnogo_otdykha/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/tovary_dlya_aktivnogo_otdykha/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/pnevmaticheskoe_oborudovanie/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/pnevmaticheskoe_oborudovanie/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/posuda_i_kukhonnyy_inventar/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/posuda_i_kukhonnyy_inventar/index.php",
	),
	array(
		"CONDITION" => "#^/bitrix/services/ymarket/order/status#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/bitrix/services/ymarket/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/online/([\\.\\-0-9a-zA-Z]+)(/?)([^/]*)#",
		"RULE" => "alias=\$1",
		"ID" => "bitrix:im.router",
		"PATH" => "/desktop_app/router.php",
	),
	array(
		"CONDITION" => "#^/catalog/klimaticheskoe_oborudovanie/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/klimaticheskoe_oborudovanie/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/bitrix/services/ymarket/order/accept#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/bitrix/services/ymarket/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/odezhda_obuv_i_aksessuary/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/odezhda_obuv_i_aksessuary/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/osnovnoy_katalog_tovarov/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/osnovnoy_katalog_tovarov/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/instrumenty_izmeritelnye/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/instrumenty_izmeritelnye/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/osveshchenie_lampochki/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/osveshchenie_lampochki/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/tovary_dlya_prazdnikov/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/tovary_dlya_prazdnikov/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/stroitelnaya_khimiya/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/stroitelnaya_khimiya/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/elektrika_lampochki/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/elektrika_lampochki/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/bitrix/services/ymarket/cart#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/bitrix/services/ymarket/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/kosmetika_i_gigiena/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/kosmetika_i_gigiena/index.php",
	),
	array(
		"CONDITION" => "#^/examples/my-components/news/#",
		"RULE" => "",
		"ID" => "demo:news",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/examples/public/language/ru/examples/my-components/news_sef.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/sistemy_khraneniya/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/sistemy_khraneniya/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/elektroinstrumenty/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/elektroinstrumenty/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/montazhnye_sistemy/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/montazhnye_sistemy/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/bytovaya_tekhnika/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/bytovaya_tekhnika/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/pomosty_lestnitsy/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/pomosty_lestnitsy/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/tovary_dlya_detey/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/tovary_dlya_detey/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/tovary_dlya_doma/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/tovary_dlya_doma/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/bytovaya_khimiya/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/bytovaya_khimiya/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/tovary_dlya_sada/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/tovary_dlya_sada/index.php",
	),
	array(
		"CONDITION" => "#^/site_el/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/tmp/site_el/personal/order/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/tmp/site_dh/personal/order/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_el/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/site_el/personal/order/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/site_dh/personal/order/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/e-store/books/reviews/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/e-store/books/reviews/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/spetsodezhda/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/spetsodezhda/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/o_kompanii/vakansii/#",
		"RULE" => "",
		"ID" => "mht:vacancies",
		"PATH" => "/tmp/o_kompanii/vakansii/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/santekhnika/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/santekhnika/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/avto_tovary/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/avto_tovary/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/kantstovary/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/kantstovary/index.php",
	),
	array(
		"CONDITION" => "#^/acrit.exportpro/(.*)#",
		"RULE" => "path=\$1",
		"ID" => "",
		"PATH" => "/acrit.exportpro/index.php",
	),
	array(
		"CONDITION" => "#^/o_kompanii/vakansii/#",
		"RULE" => "",
		"ID" => "mht:vacancies",
		"PATH" => "/o_kompanii/vakansii/index.php",
	),
	array(
		"CONDITION" => "#^/communication/forum/#",
		"RULE" => "",
		"ID" => "bitrix:forum",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/forum/public/forum/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/e-store/xml_catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/e-store/xml_catalog/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/o_kompanii/novosti/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/o_kompanii/novosti/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/soki_vody/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/soki_vody/index.php",
	),
	array(
		"CONDITION" => "#^/online/(/?)([^/]*)#",
		"RULE" => "",
		"ID" => "bitrix:im.router",
		"PATH" => "/desktop_app/router.php",
	),
	array(
		"CONDITION" => "#^/catalog/zootovary/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/zootovary/index.php",
	),
	array(
		"CONDITION" => "#^/catalog/produkty/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/produkty/index.php",
	),
	array(
		"CONDITION" => "#^/content/articles/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/content/articles/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_el/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/site_el/catalog/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/krepezh/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/krepezh/index.php",
	),
	array(
		"CONDITION" => "#^/site_el/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/tmp/site_el/catalog/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/tmp/site_dh/catalog/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/site_dh/catalog/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/content/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:photogallery_user",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/photogallery/public/photogallery_user/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/personal/lists/#",
		"RULE" => "",
		"ID" => "bitrix:lists",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/personal/lists/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/e-store/books/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/e-store/books/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_el/store/#",
		"RULE" => "",
		"ID" => "bitrix:catalog.store",
		"PATH" => "/tmp/site_el/store/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/store/#",
		"RULE" => "",
		"ID" => "bitrix:catalog.store",
		"PATH" => "/site_dh/store/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_el/store/#",
		"RULE" => "",
		"ID" => "bitrix:catalog.store",
		"PATH" => "/site_el/store/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/content/photo/#",
		"RULE" => "",
		"ID" => "bitrix:photogallery",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/photogallery/public/photogallery/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/store/#",
		"RULE" => "",
		"ID" => "bitrix:catalog.store",
		"PATH" => "/tmp/site_dh/store/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/tmp/site_dh/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/content/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/content/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_el/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/tmp/site_el/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_el/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_el/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/club/gallery/#",
		"RULE" => "",
		"ID" => "bitrix:photogallery_user",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/socialnetwork/public/ru/gallery/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/site_dh/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/site_dh/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/content/faq/#",
		"RULE" => "",
		"ID" => "bitrix:support.faq",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/iblock/public/content/faq/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/max/images/#",
		"RULE" => "",
		"ID" => "bitrix:photo",
		"PATH" => "/tmp/bitrix/components/bitrix/photo/help/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/club/forum/#",
		"RULE" => "",
		"ID" => "bitrix:forum",
		"PATH" => "/tmp/bitrix/wizards/bitrix/demo/modules/socialnetwork/public/ru/forum/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/max/images/#",
		"RULE" => "",
		"ID" => "bitrix:photo",
		"PATH" => "/tmp/bitrix/components/bitrix/news/help/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/aktsii/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/aktsii/index.php",
	),
	array(
		"CONDITION" => "#^/brands/#",
		"RULE" => "",
		"ID" => "mht:brands",
		"PATH" => "/brands/index.php",
	),
	array(
		"CONDITION" => "#^/brands/#",
		"RULE" => "",
		"ID" => "mht:brands",
		"PATH" => "/index.php",
	),
	array(
		"CONDITION" => "#^/brand/#",
		"RULE" => "",
		"ID" => "mht:offers",
		"PATH" => "/brand/index.php",
	),
	array(
		"CONDITION" => "#^%LIST#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/template/index.php",
		"SORT" => "100",
	),
);

?>